
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infraestructura.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoServicio
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoServicio()
    {

        this.ServicioSolicitado = new HashSet<ServicioSolicitado>();

    }


    public int ID { get; set; }

    public string Descripcion { get; set; }

    public int Precio { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ServicioSolicitado> ServicioSolicitado { get; set; }

}

}
